"""1.4 admin flag, job progress, user preferences

Revision ID: 16852257cc4d
Revises: c3027e371521
Create Date: 2026-07-30 21:35:40.853925
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '16852257cc4d'
down_revision = 'c3027e371521'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.alter_column('scan_images', 'view',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.add_column('scan_jobs', sa.Column('progress', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('scan_jobs', 'progress')
    op.alter_column('scan_images', 'view',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
